apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: {{.Values.nameproject}}-{{.Values.nameapp}}
  name: {{.Values.nameproject}}-{{.Values.nameapp}}
  namespace: {{.Values.nameproject}}
spec:
  replicas: {{.Values.replicaCount}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{.Values.nameproject}}-{{.Values.nameapp}}
  template:
    metadata:
      labels:
        app: {{.Values.nameproject}}-{{.Values.nameapp}}
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - image: "{{.Values.image.name}}:{{.Values.image.tag}}"
        name: {{.Values.nameproject}}-{{.Values.nameapp}}
      restartPolicy: Always
