variables:
  IMAGE_PROJECT: "devrelsurvey"
  IMAGE_NAME: "web-image"
  IMAGE_VERSION: 1.0.$CI_PIPELINE_IID
  KONTUR_REGISTRY_URL: registry.skbkontur.ru
  K8S_NAMESPACE: "devrel-survey"

stages:
- build
- deploy

build:
  stage: build
  image: docker:stable
  tags:
  - docker-build
  before_script:
  - docker login --username $REGISTRY_USER --password $REGISTRY_PASS $KONTUR_REGISTRY_URL
  script:
  - docker build --pull . --tag $KONTUR_REGISTRY_URL/$IMAGE_PROJECT/$IMAGE_NAME:$IMAGE_VERSION
  - docker push $KONTUR_REGISTRY_URL/$IMAGE_PROJECT/$IMAGE_NAME:$IMAGE_VERSION
  after_script:
   - docker logout $KONTUR_REGISTRY_URL

deploy:
  environment: staging
  variables:
    K8S_CLUSTER: staging-cl1
  image: registry.skbkontur.ru/devops_k8s/helm-client:v2.12.2
  stage: deploy
  tags:
  - kubernetes
  - staging
  before_script:
  - ENV_VAR_SUFFIX="_${CI_ENVIRONMENT_NAME}";
  - for var in $(compgen -e | grep "${ENV_VAR_SUFFIX}$"); do declare -x ${var%${ENV_VAR_SUFFIX}}="${!var}"; done
  - helm get-config $K8S_NAMESPACE $K8S_CLUSTER 
  - helm init --client-only
  script:
  - helm upgrade --install survey-web ./charts/$IMAGE_PROJECT --set image.tag=$IMAGE_VERSION --tiller-namespace=$K8S_NAMESPACE